name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "*"

jobs:
  build:
    name: Build
    uses: EasyDesk/workflows/.github/workflows/build.yml@v5
    with:
      dotnet-version: 9.x
      warnings-as-errors: true
      integration-tests-project: test/EasyDesk.RebusCompanions.IntegrationTests
      additional-test-arguments: --logger 'GitHubActions'
      build-artifact-name: build-artifacts
      projects: |
        src/EasyDesk.RebusCompanions.Scheduler.RabbitMqPostgres
        src/EasyDesk.RebusCompanions.Scheduler.RabbitMqSqlServer
        src/EasyDesk.RebusCompanions.RabbitMqEmailErrorManager

  docker-build:
    name: Build Docker Images
    needs: [build]
    strategy:
      matrix:
        include:
          - dockerfile: src/EasyDesk.RebusCompanions.Scheduler.RabbitMqPostgres/Dockerfile
            image-name: rebus-scheduler-rabbitmq-postgres
          - dockerfile: src/EasyDesk.RebusCompanions.Scheduler.RabbitMqSqlServer/Dockerfile
            image-name: rebus-scheduler-rabbitmq-sqlserver
          - dockerfile: src/EasyDesk.RebusCompanions.RabbitMqEmailErrorManager/Dockerfile
            image-name: rebus-error-manager-rabbitmq-email
    uses: EasyDesk/workflows/.github/workflows/docker-delivery.yml@v5
    with:
      dockerfile: ${{ matrix.dockerfile }}
      image-name: ${{ matrix.image-name }}
    secrets:
      registry-url: docker.io
      docker-username: easydesk
      docker-password: ${{ secrets.DOCKER_HUB_PASSWORD }}

  release:
    name: GitHub Release
    needs: [build]
    if: needs.build.outputs.should-release == 'true'
    uses: EasyDesk/workflows/.github/workflows/github-delivery.yml@v5
    with:
      release-prefix: EasyDesk.RebusCompanions
